### ISSUE TITLE
Do we need apache enum on this script?

### ISSUE THREAD

**Issue by alibkaba** [linted/linuxprivchecker#14]
@5aru @linted 
Do you both mind if we remove these two code of lines?
#L17-24
https://github.com/linted/linuxprivchecker/blob/69c9c1456c46590762ae3c778f208fdc43f592e0/linuxprivchecker.sh#L201-L205

I've yet to usefulness in them, and whenever I do need to look up apache data, its usually for specifics...not these.

Anyway, I just wanted to see what you both though about it.

**Comment by Whurbin** [comment]
I'm okay with it really. Normally I do check the scripts manually. My only reservation would be to keep it for the sake of staying in accord with the forked project. 

I have seen some usefulness for it when I've done various tests, but it's pretty rare. 

In all fairness however, I usually don't even use the script here unless I'm a little lost on a machine and have been stuck for a while; I do it all manually. It's just a good reference point.

**Comment by alibkaba** [comment]
I couldn't agree more with your last statement @5aru.
I put in a PR for it. Update linuxprivchecker.sh #15

**Comment by linted** [comment]
let's not remove functionality from the script. There may not be a ton of usefulness in every situation but that doesn't mean no one will ever use it. Instead why don't we make it a command line flag to turn that check on? 

An idea would be to put in the following three flags:
-h    Print help
-a    Run apache checks
-A    Run all checks

this will set us up to start doing better formating and making the output more manageable. Personally I would submit another flag to either turn on or off the listing of all installed packages. 

I do not think the best course of action is to ever remove functionality from this script unless it causes side affects that are undesireable.

**Comment by 5aru** [comment]
That sounds reasonable

**Comment by alibkaba** [comment]
@linted Good idea and I agree, let's not remote anything.
When I have some time, I'll try and make ours a the same or better than rebootuser's version.

**Comment by Whurbin** [comment]
This is what I think he's talking about @linted. https://github.com/rebootuser/LinEnum

**Comment by alibkaba** [comment]
Closing this issue and the PR Update linuxprivchecker.sh #15
